name: Publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
jobs:
  publish:
    runs-on: ubuntu-24.04
    env:
      DOCKER_IMAGE: educandu/mongotools
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0
      - name: Get tag from build environment
        uses: ilDug/get-tag-action@v1.0.3
        with:
          strip_v: true
        id: tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ steps.tag.outputs.version }}
            ${{ env.DOCKER_IMAGE }}:latest
